### PR TITLE
Convert sound API to using sound_manager

### PR DESCRIPTION
**Pull request by Aurelius7309**
Sound API currently has issues playing music and bypasses the modulate functionality completely. This integrates it with the sound manager at hand.

### CODE REVIEW

**Comment by MathIsFun0** [comment]
Trying to play a custom sound and getting an error on this line:
`if string.find(s.sound_code,'music') then`
because `s.sound_code` is nil
https://github.com/MathIsFun0/Cryptid/tree/sound-rework (I was using Big Cube to test if even the XChip sound would work)

**Comment by Aurelius7309** [comment]
Oops, fixed

**Comment by MathIsFun0** [comment]
Can confirm it works, a few things I want now though:
- an option to apply the pitch shifting or not
- an option to force sync with the main music tracks (this could help music tracks remain synced for a full game session if they're a few frames shorter or longer than the vanilla tracks)

**Comment by Aurelius7309** [comment]
- You can add `pitch` and `volume` fields to override the default music values, though I should probably make those work as defaults for other sounds
- It should sync the music when no_sync is absent regardless of length

**Pull request merged**
